# Site settings

# The title of your site
title: Ruiyang Zhou' Homepages
# A short description of your site's purpose
description: #Here is Ruiyang Zhou' Homepages
# To use the Cayman theme
# https://github:com/pages-themes/cayman
theme: jekyll-theme-cayman
# "true" or "false" to indicate whether to provide a download URL
show_downloads: false
# Your Google Analytics tracking ID
#google_analytics:

